var StoredFoods =[
    {   name: 'peas',
        histidine: 1,
        isoleucine: 14,
        leucine: 12,
        lysine: 15,
        methionine: 11,
        phenylalanine: 23,
        threonine: 19,
        tryptophan: 13,
        valine: 13
    },
    {   name: 'spinach',
        histidine: 9,
        isoleucine: 11,
        leucine: 8,
        lysine: 8,
        methionine: 7,
        phenylalanine: 15,
        threonine: 12,
        tryptophan: 14,
        valine: 9
    },
    {   name: 'pasta',
        histidine: 43,
        isoleucine: 37,
        leucine: 36,
        lysine: 14,
        methionine: 20,
        phenylalanine: 76,
        threonine: 44,
        tryptophan: 66,
        valine: 32
    },
    {   name: 'sweet potato',
        histidine: 4,
        isoleucine: 4,
        leucine: 3,
        lysine: 3,
        methionine: 4,
        phenylalanine: 10,
        threonine: 8,
        tryptophan: 11,
        valine: 5
    },
    {   name: 'lentils',
        histidine: 99,
        isoleucine: 76,
        leucine: 65,
        lysine: 82,
        methionine: 29,
        phenylalanine: 139,
        threonine: 84,
        tryptophan: 79,
        valine: 67
    },
    {   name: 'brazilnuts',
        histidine: 58,
        isoleucine: 37,
        leucine: 44,
        lysine: 23,
        methionine: 154,
        phenylalanine: 73,
        threonine: 35,
        tryptophan: 48,
        valine: 42
    },
    {   name: 'avocados',
        histidine: 7,
        isoleucine: 6,
        leucine: 5,
        lysine: 6,
        methionine: 5,
        phenylalanine: 11,
        threonine: 7,
        tryptophan: 9,
        valine: 6
    },
    {   name: 'kidney beans',
        histidine: 34,
        isoleucine: 29,
        leucine: 27,
        lysine: 29,
        methionine: 16,
        phenylalanine: 58,
        threonine: 30,
        tryptophan: 37,
        valine: 27
    },
    {   name: 'white rice',
        histidine: 9,
        isoleucine: 8,
        leucine: 8,
        lysine: 5,
        methionine: 9,
        phenylalanine: 16,
        threonine: 9,
        tryptophan: 11,
        valine: 9
    },
    {   name: 'green soybeans',
        histidine: 50,
        isoleucine: 41,
        leucine: 34,
        lysine: 37,
        methionine: 22,
        phenylalanine: 67,
        threonine: 49,
        tryptophan: 56,
        valine: 32
    },
    {   name: 'chickpeas (Garbanzo)',
        histidine: 81,
        isoleucine: 63,
        leucine: 54,
        lysine: 66,
        methionine: 37,
        phenylalanine: 126,
        threonine: 73,
        tryptophan: 71,
        valine: 48
    },


];

function getFoodList(){
    return StoredFoods;
}

